name: Continuous Integration

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npx biome check .
        continue-on-error: true

      - name: Build Firefox extension
        run: npm run build:firefox

      - name: Build Chrome extension
        run: npm run build:chrome

      - name: Build web version
        run: npm run build:web

      - name: Check build artifacts
        run: |
          echo "Firefox build contents:"
          ls -la dist-firefox/
          echo "Chrome build contents:"
          ls -la dist-chrome/
          echo "Web build contents:"
          ls -la dist/

      - name: Validate manifest files
        run: |
          echo "Firefox manifest:"
          cat dist-firefox/manifest.json
          echo "Chrome manifest:"
          cat dist-chrome/manifest.json
