name: Build and Release Extensions

on:
  release:
    types: [created]
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Firefox extension
        run: npm run build:firefox

      - name: Build Chrome extension
        run: npm run build:chrome

      - name: Package Firefox extension
        run: |
          cd dist-firefox
          zip -r ../varia-redirect-firefox-${{ github.ref_name }}.zip .

      - name: Package Chrome extension
        run: |
          cd dist-chrome
          zip -r ../varia-redirect-chrome-${{ github.ref_name }}.zip .

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            varia-redirect-firefox-${{ github.ref_name }}.zip
            varia-redirect-chrome-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 Release ${{ github.ref_name }}

            ### Downloads
            - 📥 [Chrome Extension](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/varia-redirect-chrome-${{ github.ref_name }}.zip)
            - 🦊 [Firefox Extension](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/varia-redirect-firefox-${{ github.ref_name }}.zip)

            ### Installation
            1. Download the appropriate extension for your browser
            2. Extract the zip file
            3. Load the extension in developer mode
            4. Configure your Aria2 connection settings

            **Full changelog**: https://github.com/${{ github.repository }}/compare/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-and-release
    if: github.event_name == 'release' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build web version for GitHub Pages
        run: npm run build:web

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
